import { Inter } from "next/font/google";
import "./globals.css";

import CustomNavbar from "./components/CustomNavbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Bank Account Open",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <CustomNavbar/>
      <div className="w-full Body">
      {children}
      </div>
      </body>
    </html>
  );
}
